### ISSUE TITLE
TPAC Prep: Making substantial changes to EPUB - the future of EPUB

### ISSUE THREAD

**Issue by wareid** [w3c/pm-wg#6]
Creating an issue to collect conversation and ideas prior to TPAC. 

Questions we need to answer: 
* What changes do we want to make to EPUB in coming years? 
* What need would these changes address, what would the impact be? 
* Do these changes demand an immediate re-chartering, and if not, what do we need to put into the next charter? (Current Charter expires June 2025)
* Are we still updating EPUB 3 or talking about a new version entirely? 

One of the challenges related to future EPUB development is the question of HTML serialization. We've discussed this various times over the years: 
* https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-05-30-pwg.html#section2
* 

Some notable comments that likely still hold true: 
* https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2018/2018-05-30-pwg.html#:~:text=Luc%20Audrain%3A,for%20our%20assets

**Comment by iherman** [comment]
Reflecting on one point:

> Are we still updating EPUB 3 or talking about a new version entirely?

Technically, I think this is a question we can only answer if we know the changes we do. Looking at some examples:

- If we add an explicit functionality for WebToons, I believe it would be an EPUB 3.4 (not a major change, but some technical add-on)
- If we open the door to HTML5, that _may_ be a major change, ie, EPUB4, but I am not even sure, because it would not change functionality
- If we define standard annotations, then that might not touch the current specification, which could remain EPUB 3.3. The annotation could become the subject of a separate standard alongside the reading systems' document (and relevant to RS implementers only).

My question on this is rather: what would the publishing industry accept us to do? What are our constraints from a business point of view? What would epubcheck do? What does backward compatibility mean with new features?

**Comment by mattgarrish** [comment]
> * If we open the door to HTML5, that _may_ be a major change, ie, EPUB4, but I am not even sure, because it would not change functionality

The nav doc has historically been one of the big sticking points. If allowing html in the spine is all we're talking about, then it's just another top-level content document type. If we get bogged down in creating a new navigation document definition because epub:type isn't valid in html, then we further raise the breakage factor for existing reading systems and possibly put this in the realm of an epub 4.

But we don't have an svg nav doc so you can have all svg, so I don't know that there's a lot of benefit in an html-only version if we're trying to make the change as minimally disruptive as possible.

**Comment by mattgarrish** [comment]
Minor nit, but for clarity we should be talking about adding support for the html syntax, not html5. HTML5 doesn't really exist anymore as a thing, and, if it did, the xml syntax we use is html5, too.

**Comment by iherman** [comment]
> […] If we get bogged down in creating a new navigation document definition because epub:type isn't valid in html, then we further raise the breakage factor for existing reading systems and possibly put this in the realm of an epub 4.

The compromise position is that we would continue requiring the nav file to be xhtml for the reasons you quote. It may be an extra item for epubcheck but, otherwise, I do not think it would be a major problem.

**Comment by gregoriopellegrino** [comment]
I try to share some scattered thoughts, while I haven't fully formulated my complete perspective yet, here are some of the ideas I've been meditated over the past few weeks.

First, I must admit that I'm somewhat apprehensive about moving from a secure situation, where every content of the EPUB publication is defined according to precise and validatable rules, towards a very open solution where it might be very difficult to validate content conformity.

We have examples of other document formats that have opened up more possibilities over the years and have effectively become distribution formats only, where it's nearly impossible to make content modifications without returning to the source file and re-exporting.

Working with publishers, we understood the need to using EPUB files as an asset, not just as a publication format. Consider the whole issue of backlist regarding the European Accessibility Act, where publishers are remediating very old files to update them in terms of version and accessibility.

In this context we think of EPUB as structured content, not as consumable output - something that can be reused as a starting point for a new publication. Something that can be automatically updated.

More and more we see the EPUB standard used as an internal B2B format. It's not used so much for interoperability (for example when the publisher that publish the digital book also controls the reading solution, and the ebook can't be read outside that reading solution), but as a standardized packaging method, validatable and benefiting from many free tools already available (EPUBCheck, Ace by DAISY, etc.) or at widely developed authoring tools, reading solutions, etc.

Many of the workflows and tools I'm thinking of and that are used daily in the supply chain, including EPUBCheck, are based on technologies closely linked to XML such as XSLT, XPATH, and XSD... How could we achieve similar results, in an equally efficient and standardized way in HTML?

My proposal would therefore be to open the doors to HTML, leaving it to the content creator to decide whether to use XHTML or HTML. Some actors in the supply chain could add restrictions and ask to receive and manage only EPUBs containing XHTML...

Finally, I wonder: has an opinion on this topic been requested from the Business Group? I think a change in this direction could have a significant impact on many companies in the supply chain.

**Comment by avneeshsingh** [comment]
The main question looking at short term is, what serious problems are we envisioning if EPUB 3 remains in XHTML profile of HTML 5 for next 4 or 5 years?
If we do not see a disruption in status quo then we should go on the path of incubation, and take time to figure out a new publishing format based on future proof HTML. We did web publications in a hurry, but if we approach this problem in a systematic way and take time to figure it out, I think we will get appropriate results.

**Comment by dazrand** [comment]
From a publisher point of view, shifting EPUB to using only HTML should be a large enough change to require a new format and new charter. Even when the epub:type is only used for publisher processes, a shift to HTML only will have significant consequences on internal systems as expected, but this will influence the distribution chain. This would change some of the fundamental systems publishers use in generation, distribution, and consumption. 

Beyond that, as noted, a careful approach needs to be taken. A list of all the potential issues should be shared to ensure everyone has a clear idea of the expected impacts. 

Since publishers are already focused on other issues with a 2025 significance, letting these changes wait until the next charter helps them concentrate resources on the 2025 issue.
